apiVersion: apps/v1
kind: Deployment
metadata:
  name: itdt-front
  labels:
    app: itdt
spec:
  replicas: 2
  selector:
    matchLabels:
      app: itdt
  template:
    metadata:
      labels:
        app: itdt
    spec:
      containers:
      - name: itdt-front
        image: ifilyaninitmo/itdt-contained-frontend:master 
        ports:
        - containerPort: 3000        
        env:
        - name: REACT_APP_USERNAME
          value: "Qwerty"
        - name: REACT_APP_COMPANY_NAME
          value: "ICANT"